{{- $webserverConfig := .Values.webserver | default nil}}
{{- $hpaConfig := $webserverConfig.hpa | default nil}}

{{- if $hpaConfig.enabled | default false }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "nameService" . }}
  labels:
    {{- include "labels.common" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "nameService" . }}
  minReplicas: {{ default 1 $hpaConfig.minReplicas }}
  maxReplicas: {{ default 20 $hpaConfig.maxReplicas }}
  metrics:
  {{- if $hpaConfig.metrics }}
  {{ toYaml $hpaConfig.metrics | trim | nindent 8 }}
  {{- end }}
{{- end }}
