{{- $root := . -}}

{{- range $jobName, $jobConfig := .Values.preReleaseJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $root.Chart.Name }}-pre-release-hook-{{ $jobName }}
  labels:
    {{- include "labels.common" $root | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: {{ $root.Chart.Name }}-hook
      labels:
        {{- include "labels.common" $root | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ $jobName }}
        image: {{ $root.Values.global.image }}
        command: {{- range $args := $jobConfig.command }}
        - {{ $args | quote }}
        {{- end }}
        env:
        {{- include "service.config" $root | indent 10 }}
---
{{- end }}
