apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "labels.common" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
type: Opaque
data:
#  redis_dsn: {{ default "redis://localhost:6379/1" .Values.redisDsn | b64enc }}
#  mongodb_dsn: {{ default "mongodb://localhost:27017" .Values.mongodbDsn | b64enc }}
#  rabbitmq_dsn: {{ default "rabbitmq://guest:guest@localhost//" .Values.rabbitmqDsn | b64enc }}
#  pgsql_dsn: {{ default "pgsql://postgres:postgres@postgres:5432/db_00_base_tpl?charset=UTF-8&serverVersion=10.1" .Values.pgsqlDsn | b64enc }}

