apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels.name" .Chart.Name | indent 4 }}
    {{- include "labels.common" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    {{- include "labels.webserver" . | indent 4 }}
